CREATE TABLE IF NOT EXISTS public.teams (
  id integer PRIMARY KEY,
  name text NOT NULL DEFAULT '',
  members text[] NOT NULL DEFAULT ARRAY[]::text[],
  score integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item text NOT NULL,
  points integer NOT NULL CHECK (points >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id integer NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
  item_id integer NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  time_submitted timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'denied')),
  reviewed_at timestamptz,
  reviewed_by integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS submissions_one_pending_per_team_item
  ON public.submissions (team_id, item_id)
  WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS submissions_one_approved_per_team_item
  ON public.submissions (team_id, item_id)
  WHERE status = 'approved';

CREATE INDEX IF NOT EXISTS submissions_item_status_idx
  ON public.submissions (item_id, status, time_submitted DESC);

CREATE INDEX IF NOT EXISTS submissions_team_status_idx
  ON public.submissions (team_id, status, time_submitted DESC);

CREATE OR REPLACE FUNCTION public.approve_submission(
  p_submission_id integer,
  p_reviewed_by integer
)
RETURNS SETOF public.submissions
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  approved_row public.submissions%ROWTYPE;
  item_points integer;
BEGIN
  UPDATE public.submissions
  SET status = 'approved',
      reviewed_at = now(),
      reviewed_by = p_reviewed_by
  WHERE id = p_submission_id
    AND status = 'pending'
  RETURNING * INTO approved_row;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT points INTO item_points
  FROM public.items
  WHERE id = approved_row.item_id;

  UPDATE public.teams
  SET score = score + COALESCE(item_points, 0)
  WHERE id = approved_row.team_id;

  RETURN NEXT approved_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.deny_submission(
  p_submission_id integer,
  p_reviewed_by integer
)
RETURNS SETOF public.submissions
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  denied_row public.submissions%ROWTYPE;
BEGIN
  UPDATE public.submissions
  SET status = 'denied',
      reviewed_at = now(),
      reviewed_by = p_reviewed_by
  WHERE id = p_submission_id
    AND status = 'pending'
  RETURNING * INTO denied_row;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  RETURN NEXT denied_row;
END;
$$;
