INSERT INTO public.teams (id, name, members, score)
VALUES
  (7687, 'Team 1', ARRAY[]::text[], 0),
  (6215, 'Team 2', ARRAY[]::text[], 0),
  (9277, 'Team 3', ARRAY[]::text[], 0),
  (1023, 'Team 4', ARRAY[]::text[], 0),
  (4136, 'Team 5', ARRAY[]::text[], 0)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    members = EXCLUDED.members,
    score = EXCLUDED.score;

INSERT INTO public.items (item, points, category, display_order) VALUES
('A water fountain', 5, 'FIND IT IN THE MALL', 1),
('A store with a line out the door', 5, 'FIND IT IN THE MALL', 2),
('A red bench or red seating area', 5, 'FIND IT IN THE MALL', 3),
('A horse', 5, 'FIND IT IN THE MALL', 4),
('A store that sells exclusively one type of product (e.g. only socks, only candles)', 5, 'FIND IT IN THE MALL', 5),
('A "Sale 50% off" sign in a store window', 5, 'FIND IT IN THE MALL', 6),
('A plant or tree inside the mall', 5, 'FIND IT IN THE MALL', 7),
('A store that starts with the letter "H"', 5, 'FIND IT IN THE MALL', 8),
('A map of the mall with a "You Are Here" marker', 5, 'FIND IT IN THE MALL', 9),
('A photo taken on the highest floor of the mall looking down', 5, 'FIND IT IN THE MALL', 10),
('A restaurant with a menu visible from outside', 5, 'FIND IT IN THE MALL', 11),
('A storefront with Christmas/holiday decorations still up', 5, 'FIND IT IN THE MALL', 12),
('A "wet floor" sign', 5, 'FIND IT IN THE MALL', 13),
('A neon sign', 5, 'FIND IT IN THE MALL', 14),
('An escalator going up AND one going down in the same photo', 10, 'FIND IT IN THE MALL', 15),
('A shoe with a price tag over $500', 10, 'FIND IT IN THE MALL', 16),
('A company who has previously sponsored Hack Western (based on our spon package)', 10, 'FIND IT IN THE MALL', 17),
('Something that costs exactly $1 or less', 10, 'FIND IT IN THE MALL', 18),
('Find a "Hack Western purple" coloured item anywhere in the mall', 10, 'FIND IT IN THE MALL', 19),
('Find something with a Western University or Ivey logo on it', 10, 'FIND IT IN THE MALL', 20),
('Find something in the mall that costs more than $1,000 (show price tag)', 10, 'FIND IT IN THE MALL', 21),
('A tuff fit', 10, 'OUTFIT CHALLENGES', 22),
('Take a photo that looks like it could be a stock photo (cheesy smiles, thumbs up, etc.)', 10, 'OUTFIT CHALLENGES', 23),
('Show off your best "dad fit"', 15, 'OUTFIT CHALLENGES', 24),
('Show off your best "tech bro fit"', 15, 'OUTFIT CHALLENGES', 25),
('Put on your best "business casual" fit', 15, 'OUTFIT CHALLENGES', 26),
('The most "western" outfit you can come up with (up for interpretation)', 15, 'OUTFIT CHALLENGES', 27),
('Recreate a mannequin''s exact outfit (edit outfit and mannequin side-by-side)', 15, 'OUTFIT CHALLENGES', 28),
('Two team members: one wearing a purple shirt and one wearing a green shirt', 20, 'OUTFIT CHALLENGES', 29),
('Get a team member to put on an "emo" outfit', 20, 'OUTFIT CHALLENGES', 30),
('Get a boy on your team to put on a dress', 30, 'OUTFIT CHALLENGES', 31),
('Take a photo that looks like it could be a LinkedIn profile picture', 5, 'CREATIVE / CHAOS', 32),
('Full team mirror selfie', 5, 'CREATIVE / CHAOS', 33),
('Take a photo that looks like a real estate listing (someone posed proudly in front of a store like they own it)', 5, 'CREATIVE / CHAOS', 34),
('A photo where the whole team is reflected in a store window', 5, 'CREATIVE / CHAOS', 35),
('The Hack Western website on a MacBook', 10, 'CREATIVE / CHAOS', 36),
('At least two team members pretending to be mannequins in a store window', 10, 'CREATIVE / CHAOS', 37),
('Take a photo that looks like an album cover', 10, 'CREATIVE / CHAOS', 38),
('A photo of your whole team on a bench', 10, 'CREATIVE / CHAOS', 39),
('Recreate a famous painting or statue pose', 15, 'CREATIVE / CHAOS', 40),
('Get a food court worker to write "HW13" on a cup or container', 20, 'CREATIVE / CHAOS', 41),
('A security guard', 10, 'STRANGER CHALLENGES', 42),
('A stranger giving you a thumbs up', 15, 'STRANGER CHALLENGES', 43),
('Find someone with a nose piercing', 15, 'STRANGER CHALLENGES', 44),
('Get a stranger to take a photo of your whole team jumping at the same time', 15, 'STRANGER CHALLENGES', 45),
('Arm wrestle with a stranger', 20, 'STRANGER CHALLENGES', 46),
('You and a stranger hitting the scuba', 20, 'STRANGER CHALLENGES', 47),
('Get a stranger to do a hand heart with a team member', 20, 'STRANGER CHALLENGES', 48),
('A stranger wearing the HW12 pit vipers', 20, 'STRANGER CHALLENGES', 49),
('A stranger holding up a ''W'' with their fingers', 20, 'STRANGER CHALLENGES', 50),
('A stranger flexing their muscles next to you', 20, 'STRANGER CHALLENGES', 51),
('A stranger who looks like someone on your team', 20, 'STRANGER CHALLENGES', 52),
('Sitting next to a stranger in the food court', 20, 'STRANGER CHALLENGES', 53),
('A stranger holding a sign that says "Hack Western 13!" (you provide the sign)', 20, 'STRANGER CHALLENGES', 54),
('Get 2 people to hit the sea lion on a food court table', 25, 'STRANGER CHALLENGES', 55),
('A stranger letting you try on their hat or accessory', 25, 'STRANGER CHALLENGES', 56),
('Find a stranger willing to swap shoes with a team member for a photo', 25, 'STRANGER CHALLENGES', 57)
ON CONFLICT (display_order) DO UPDATE
SET item = EXCLUDED.item,
    points = EXCLUDED.points,
    category = EXCLUDED.category;